#!/bin/bash

#set -e
#set -x

CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`

echo "You are currently working on $CURRENT_BRANCH"
DIFF_RESULT=$(git diff-index --quiet HEAD)
if [ ! -z ${DIFF_RESULT} ]; then
  echo "Stashing changes..."
  git stash
  STASHED_CHANGES=true
fi

if [ $CURRENT_BRANCH != "master" ]; then
  git checkout master
fi

git svn rebase

if [ $CURRENT_BRANCH != "master" ]; then
  git merge --no-ff $CURRENT_BRANCH
  git commit --amend
fi

git svn dcommit 

if [ $CURRENT_BRANCH != "master" ]; then
  echo "Switching back to $CURRENT_BRANCH..."
  git checkout $CURRENT_BRANCH
  git merge master
fi

if [ $STASHED_CHANGES ]; then
  echo "Re-applying stashed changes..."
  git stash pop
fi

